apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pri6jn25v-nodejs 
  janus-idp.io/tekton: pri6jn25v-nodejs
  backstage.io/kubernetes-id: pri6jn25v-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pri6jn25v-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml